export enum BlockType {
  AIR = 0,
  GRASS = 1,
  DIRT = 2,
  STONE = 3,
  SAND = 4,
  WATER = 5,
  WOOD = 6,
  LEAVES = 7,
  COBBLESTONE = 8,
  BEDROCK = 9,
  SNOW = 10,
  COAL_ORE = 11,
  IRON_ORE = 12,
  PLANKS = 13,
  GLASS = 14,
  BRICK = 15,
}

export const BLOCK_NAMES: Record<BlockType, string> = {
  [BlockType.AIR]: 'Air',
  [BlockType.GRASS]: 'Grass',
  [BlockType.DIRT]: 'Dirt',
  [BlockType.STONE]: 'Stone',
  [BlockType.SAND]: 'Sand',
  [BlockType.WATER]: 'Water',
  [BlockType.WOOD]: 'Wood',
  [BlockType.LEAVES]: 'Leaves',
  [BlockType.COBBLESTONE]: 'Cobblestone',
  [BlockType.BEDROCK]: 'Bedrock',
  [BlockType.SNOW]: 'Snow',
  [BlockType.COAL_ORE]: 'Coal Ore',
  [BlockType.IRON_ORE]: 'Iron Ore',
  [BlockType.PLANKS]: 'Planks',
  [BlockType.GLASS]: 'Glass',
  [BlockType.BRICK]: 'Brick',
};
